---
- name: Web Server Installation
  hosts: localhost
  tasks:
    - name: create R53 record
      route53:
        zone: devopsplus.net
        record: wordpress.devopsplus.net
        type: A
        ttl: 7200
        value: 3.12.41.139
        state: present
        wait: yes
